# Generated by Django 4.0 on 2023-10-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
            ],
        ),
    ]
