# Generated by Django 4.0 on 2023-10-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_menu_alter_category_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.menu'),
            preserve_default=False,
        ),
    ]
